### PR TITLE
Add test suite

### PR DESCRIPTION
**Pull request by tyler43636**
I've been learning about testing lately and I'd like to work on a test suite for imager. I'm using codeception with plans of making an integration test suite so that we can test the models and database interactions.

 Interested?

### CODE REVIEW

**Comment by atrauzzi** [comment]
Definitely, flesh it out a bit more and we'll look at things as they progress.

If possible, I'd encourage you to stick to the code conventions.  If you use PHPstorm, I can give you a copy of my formatting preferences?

**Comment by tyler43636** [comment]
Sure, send me your php storm settings! I've made some progress already, but I'm going to close this PR until get a little more done.

**Comment by atrauzzi** [comment]
Hey @tyler43636, here's a gist with the settings: https://gist.github.com/atrauzzi/86a5b04dc5fa33c879ec

**Comment by tyler43636** [comment]
Thanks! It's coming along nicely. I should have something to show you sometime next week.

**Comment by atrauzzi** [comment]
Hopefully you got my ping about moving over to atrauzzi/imager.  Coordination of this library will be moving over there as I'm switching employers in a few weeks!

(I'll fix up the namespaces and update packagist soon.)

**Comment by tyler43636** [comment]
I do now!

**Pull request closed without merging**
